lista = []
frase = input('Digite sua frase: ')
frase.split()
qtd = len(frase.split())
lista.append(frase)
print(qtd)
print(lista)
pa = input('Digite a palavra que você quer substituir: ')
pn = input('Digite a palavra nova: ')
lista= frase.replace(pa, pn)
print(lista)
frase_inversa = ' '. join(lista.split()[::-1])
print(frase_inversa)
cont = input('Digite a letra que você quer contar: ')
cont2 = lista.count(cont)
print(cont2)
print('\n--- Resumo das Informações ---')
print(f'Frase original: {frase}')
print(f'a quantidade de palavras é: {qtd}')
print(f'Palavra substituída: {pa} por {pn}')
print(f'Frase após substituição: {lista}')
print(f'Frase invertida (palavras): {frase_inversa}')
print(f'a quantidade de vezes que aparece a letra {cont} é {cont2} vezes!')
print('\n-------------------------------')


